name: Branch - Build, Test, Release Beta & Publish

on:
  workflow_dispatch:
    branches-ignore:
      - main

permissions:
  contents: write
  packages: write
  actions: write
  checks: write
  pull-requests: write
  id-token: write

jobs:
  build-lint:
    name: Build, Lint, and Test
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-setup-lint-build.yml@v3.1.1
    secrets: inherit
    with:
      use-vitest: true

  publish-beta-version:
    name: Get Beta Version
    needs: build-lint
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-publish-npm-beta-package.yml@v1.0.20
    with:
      build-directory: dist
    secrets: inherit
