name: Main - Build, Test, Update Release & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  pages: write
  id-token: write

jobs:
  build-lint:
    name: Build & Lint
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-setup-lint-build.yml@v1.0.18
    secrets: inherit

  # test:
  #   name: Test
  #   uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-test-storybook.yml@v1.0.14
  #   secrets: inherit

  update-release:
    name: Update Release
    needs: [build-lint] #[build-lint, test]
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/update-release.yml@v1.0.18
    with:
      release-type: 'node'

  publish:
    name: Publish NPM Package
    needs: update-release
    if: ${{ needs.update-release.outputs.release_created }}
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-publish-npm-package.yml@v1.0.18
    with:
      build-directory: dist
    secrets: inherit

  deploy-documentation:
    name: Deploy Documentation
    needs: update-release
    if: ${{ needs.update-release.outputs.release_created }}
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-publish-storybook-documentation.yml@v1.0.18
